name: Build and Deploy Nuxt3 SSR to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. Build SSR Nuxt app
      - name: Build SSR Nuxt app
        run: yarn build

      # 5. Zip project (รวมไฟล์สำคัญสำหรับ SSR)
      - name: Zip project for Azure
        run: |
          zip -r nuxt3-app.zip . \
            -x "*.git*" "*.github*" "node_modules/*" \
            -x "*.env*" "*.log" "README.md"
          ls -l nuxt3-app.zip  # ตรวจสอบไฟล์ zip

      # 6. Deploy zip ไป Azure
      - name: Deploy SSR to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: Yadommm  # ชื่อ App/Slot ของคุณ
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: nuxt3-app.zip
          enable-oryx-build: false  # ใช้ build ของเราเอง