name: Build and Deploy Nuxt3 SSR to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. Build SSR Nuxt app
      - name: Build SSR Nuxt app
        run: yarn build

      # 5. Create zip of entire project
      - name: Zip project
        run: zip -r nuxt3-app.zip . -x "*.git*" "*.github*" "node_modules/*"

      # 6. Deploy to Azure slot
      - name: Deploy SSR to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: Yadommm  # ใส่ชื่อ slot / app ของคุณ
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: nuxt3-app.zip
          enable-oryx-build: false  # ปิด Oryx build ให้ใช้ไฟล์ที่เราสร้างเอง